/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BackgroundProcessor: typeof import('./src/components/PropsTable/BackgroundProcessor.vue')['default']
    ColorPicker: typeof import('./src/components/PropsTable/ColorPicker.vue')['default']
    ComponentList: typeof import('./src/components/ComponentList.vue')['default']
    EditGroup: typeof import('./src/components/EditGroup.vue')['default']
    EditWrapper: typeof import('./src/components/EditWrapper.vue')['default']
    IconSwitch: typeof import('./src/components/PropsTable/IconSwitch.vue')['default']
    ImageProcessor: typeof import('./src/components/PropsTable/ImageProcessor.vue')['default']
    InlineEdit: typeof import('./src/components/InlineEdit.vue')['default']
    LegoImage: typeof import('./src/components/lego/LegoImage.vue')['default']
    LegoShape: typeof import('./src/components/lego/LegoShape.vue')['default']
    LegoText: typeof import('./src/components/lego/LegoText.vue')['default']
    PropsTable: typeof import('./src/components/PropsTable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShadowPicker: typeof import('./src/components/PropsTable/ShadowPicker.vue')['default']
    StyledUploader: typeof import('./src/components/StyledUploader/index.vue')['default']
    Uploader: typeof import('./src/components/StyledUploader/Uploader.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
